site_name: c64tools
site_url: https://github.com/dkrajzew/c64tools
site_description: c64 Python helper. 
site_author: Daniel Krajzewicz
docs_dir: ./docs

repo_url: https://github.com/dkrajzew/c64tools.git
edit_uri: ""

theme:
    name: material
    custom_dir: ./docs/materials_ext
    font: false
    palette:
        primary: blue
        
extra_css:
    - stylesheets/extra.css
    - stylesheets/prism.css

extra_javascript:
    - js/prism.js

nav:
    - Home: index.md
    - Installation: install.md
    - Usage: 
        - charpacker: use_charpacker.md
        - charset2png: use_charset2png.md
        - mem2png: use_mem2png.md
        - filemerge: use_filemerge.md
    - Links: links.md
    - Code Docs:
        - structures: api_structures.md
        - filemerge: api_filemerge.md
        - charpacker: api_charpacker.md
        - charset2png: api_charset2png.md
        - mem2png: api_mem2png.md
    - ChangeLog: changes.md
    - License (BSD): license.md
    - Legal: legal.md

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2016&ndash;2025 Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [./c64tools]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"